name: Download DEB Packages for Offline Use
'on':
  push:
    branches:
      - main

defaults:
  run:
    shell: 'bash -el {0}'
jobs:
  build:
    name: '${{ matrix.name }}- ${{ matrix.arch }}'
    runs-on: '${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            os: ubuntu-22.04
            #os: ubuntu-latest
            arch: x86
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: download debs
        run: |
          FILEID="1I0oqg9RWD6yGe6ukhUEYggnTg1yunIPP"
          FILENAME="debs.zip"
          CONFIRM=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies \
          --no-check-certificate "https://docs.google.com/uc?export=download&id=${FILEID}" -O- \
          | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1/p')
          
          wget --load-cookies /tmp/cookies.txt \
          "https://docs.google.com/uc?export=download&confirm=${CONFIRM}&id=${FILEID}" \
          -O "${FILENAME}"
          rm -f /tmp/cookies.txt
          
          unzip debs.zip

      - name: install
        run: |
            cd debs
            sudo dpkg -i *.deb
            gmt
