name: Download DEB Packages for Offline Use
'on':
  push:
    branches:
      - main

defaults:
  run:
    shell: 'bash -el {0}'
jobs:
  build:
    name: '${{ matrix.name }}- ${{ matrix.arch }}'
    runs-on: '${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            os: ubuntu-22.04
            #os: ubuntu-latest
            arch: x86
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: download debs
        run: |
            wget https://drive.google.com/file/d/1I0oqg9RWD6yGe6ukhUEYggnTg1yunIPP/view?usp=drive_link
            unzip debs.zip

      - name: install
        run: |
            cd debs
            sudo dpkg -i *.deb
            gmt
